version: '3.7'
services:
  downloads:
    image: nginx:latest
    volumes:
      - "./downloads/files:/files"
      - "./downloads/conf:/etc/nginx/conf.d"
    labels:
      - traefik.http.routers.downloads-${ENVIRONMENT}.rule=Host(`dl.${WEB_BASE_URL}`)
      - traefik.http.routers.downloads-${ENVIRONMENT}.entrypoints=websecure
      - traefik.http.routers.downloads-${ENVIRONMENT}.tls.certresolver=myresolver
      - traefik.http.routers.downloads-${ENVIRONMENT}.tls=true
      - traefik.docker.network=minecraft
    networks:
      - minecraft
networks:
  minecraft:
    driver: bridge
